# Generated by Django 2.2.3 on 2019-07-19 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='summercamp',
            name='marks',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
